Notes = [
    /* Szablon:
    {
        "Nazwa": "NAZWA",
        "Link": "LINK",
        "Semestr": "___",
        "Przedmiot": "PRZEDMIOT",
        "Typ": "WYK/ĆWI/LAB",
        "Opis": "OPIS",
        "Data Dodania": "DD.MM.YYYY",
        "Tagi": [["NAZWA", "KLASA_CSS"], ...],
    },
    */
    {
        "Nazwa": "Notatka z Algorytmów",
        "Link": "https://docs.google.com/document/d/1FySY5F8-b4vS5vgapZ9qYbU_V4plD-rO/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Algorytmy i Struktury Danych",
        "Typ": "WYK",
        "Opis": "Przepisane notatki odręczne z wykładów do '.docx'.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Długie", "Tag_Red"]],
    },
    {
        "Nazwa": "Rozwiązania Zadań z Algorytmów",
        "Link": "https://drive.google.com/drive/folders/1yPOR0xEMxs6y9iozkqX2fPkWT8j9u3jQ?usp=sharing",
        "Semestr": "2",
        "Przedmiot": "Algorytmy i Struktury Danych",
        "Typ": "WYK",
        "Opis": "Zdjęcia rozwiązanych zadań z przykładów i zadań domowych.",
        "Data Dodania": "04.07.2023",
        "Tagi": [[".jpg", "Tag_LightBlue"]]
    },
    {
        "Nazwa": "Notatka z Elektroniki",
        "Link": "https://docs.google.com/document/d/1zu1gSv3h2jwVG57Nb15VNuegcS2MmMrW/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Elektrotechniki i Elektroniki",
        "Typ": "WYK",
        "Opis": "Przerobione materiały z elektroniki.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Długie", "Tag_Red"]]
    },
    {
        "Nazwa": "All-In-One Przykłady Ze Statystyki",
        "Link": "https://docs.google.com/spreadsheets/d/10fj92JV-Dmfty0xuCGCUKZqSKCQKMgtl/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Statystyki",
        "Typ": "ĆWI",
        "Opis": "Przerobione przykłady z zajęć.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["Nie Dokończone", "Tag_Black"], [".xlsx", "Tag_Green"]],
    },
    {
        "Nazwa": "Excele z Lekcji",
        "Link": "https://docs.google.com/spreadsheets/d/1-aGamF2Ne6W0oPxkQ3zck6miCMf2vH2Q/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Statystyka",
        "Typ": "ĆWI",
        "Opis": "Zbiór najważniejszych Excelów z zajęć.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["Z Lekcji", "Tag_Purple"], [".xlsx", "Tag_Green"]],
    },
    {
        "Nazwa": "Teoria Ze Statystyki v1",
        "Link": "https://docs.google.com/document/d/10SUZaOgxJkb3PXj0UB24coSYJcWQtMAy/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Statystyki",
        "Typ": "ĆWI",
        "Opis": "Zbiór tematów z teorii, potrzebnych do zadań z Excela.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["Nie Dokończone", "Tag_Black"], [".docx", "Tag_Blue"]],
    },
    {
        "Nazwa": "Teoria Ze Statystyki v2",
        "Link": "https://docs.google.com/document/d/1-QEmk1I7nY4DHwh0eL7fzVu-X3RuTAfE/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Statystyki",
        "Typ": "ĆWI",
        "Opis": "Poprawiona wersja. Pojęcia i wzory potrzebne do zaliczenia.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"],],
    },
    {
        "Nazwa": "Rozwiązania Zadań Z Algorytmów",
        "Link": "https://drive.google.com/file/d/1973OjdZ6UPz04QSEVSDHBfq4nAA_mXmN/view?usp=sharing",
        "Semestr": "2",
        "Przedmiot": "Algorytmy i Struktury Danych",
        "Typ": "LAB",
        "Opis": "Rozwiązania wszystkich zadań z labów z algorytmów.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["Nie Dokończone", "Tag_Black"], [".ipynb", "Tag_Gray"]],
    },
    {
        "Nazwa": "Teoria Z Matematyki",
        "Link": "https://docs.google.com/document/d/1yxILXqchGWLbXnCAGNScqg5EFEp4HYbJ/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Matematyka",
        "Typ": "WYK",
        "Opis": "Notatka z teorii z wykładów z matematyki.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["Nie Dokończone", "Tag_Black"], [".docx", "Tag_Blue"]],
    },
    {
        "Nazwa": "Polecenia Cisco",
        "Link": "https://docs.google.com/document/d/1VoiaElkw0o0K4ZVoQ3-rkYqZLedokKEp/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "1",
        "Przedmiot": "CCNA",
        "Typ": "LAB",
        "Opis": "Spis poleceń używanych na labach i zaliczeniu z CCNA.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"],],
    },
    {
        "Nazwa": "Zagadnienia Z Programowania",
        "Link": "https://docs.google.com/document/d/1WYgtHKWydYKh0K-F7NbaZlfTcUCoXwmu70V01F51Nww/edit?usp=sharing",
        "Semestr": "1",
        "Przedmiot": "Wstęp Do Programowania",
        "Typ": "LAB",
        "Opis": "Spis tematów z wykładów z programowania, bardzo ogólnikowe.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"],],
    },
]