Notes = [
    //! TODO: Szablon
    /* Szablon:
    {
        "Nazwa": "NAZWA",
        "Link": "LINK",
        "Semestr": "___",
        "Przedmiot": "PRZEDMIOT",
        "Typ": "WYK/ĆWI/LAB/KON",
        "Opis": "OPIS",
        "Data Dodania": "DD.MM.YYYY",
        "Tagi": [["NAZWA", "KLASA_CSS"], ...],
        "Autor": "AUTOR",
    },
    */

    //! TODO: Nowe

    //! TODO: Semestr 3
    {
        "Nazwa": "Notatka z Współczesnej Kultury Informacyjnej",
        "Link": "https://docs.google.com/document/d/1_GARPdVhDi9MWQlb3m5vb7jhGwCeHV0s/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "3",
        "Przedmiot": "Współczesna Kultura Informacyjna",
        "Typ": "WYK",
        "Opis": "Przepisane prezentacje z lekcji. Z pierwszej lekcji brak notatki, zajęcia były stacjonarnie.",
        "Data Dodania": "DD.MM.YYYY",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Zaoczne", "Tag_Brown"], ["WIP","Tag_Black"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Notatka z Ochrony Własności Intelektualnej",
        "Link": "https://docs.google.com/document/d/18d2KJe2tQ6HdS6a8XxVwwL4fIjV1dMD9/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "3",
        "Przedmiot": "Ochrona Własności Intelektualnej",
        "Typ": "WYK",
        "Opis": "Notatka z wykładów z Ochrony Własności Intelektualnej, napisane na podstawie prezentacji",
        "Data Dodania": "14.11.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Zaoczne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Notatka z Architektury",
        "Link": "https://docs.google.com/document/d/18OLh7JnnYaTIt0FhoHegtdKc3B8X5ZOW/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "3",
        "Przedmiot": "Architektura Systemów Komputerowych",
        "Typ": "WYK",
        "Opis": "Notatka z wykładów z Architektury Systemów Komputerowych",
        "Data Dodania": "06.10.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Zaoczne", "Tag_Brown"], ["WIP","Tag_Black"]],
        "Autor": "Hubsik",
    },

    //! TODO: Semestr 2
    {
        "Nazwa": "Notatka z Algorytmów",
        "Link": "https://docs.google.com/document/d/1FySY5F8-b4vS5vgapZ9qYbU_V4plD-rO/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Algorytmy i Struktury Danych",
        "Typ": "WYK",
        "Opis": "Przepisane notatki odręczne z wykładów do '.docx'.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Długie", "Tag_Red"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Rozwiązania Zadań z Algorytmów",
        "Link": "https://drive.google.com/drive/folders/1yPOR0xEMxs6y9iozkqX2fPkWT8j9u3jQ?usp=sharing",
        "Semestr": "2",
        "Przedmiot": "Algorytmy i Struktury Danych",
        "Typ": "WYK",
        "Opis": "Zdjęcia rozwiązanych zadań z przykładów i zadań domowych.",
        "Data Dodania": "04.07.2023",
        "Tagi": [[".jpg", "Tag_Teal"], ["Zadanie Domowe", "Tag_Pink"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Notatka z Elektroniki",
        "Link": "https://docs.google.com/document/d/1zu1gSv3h2jwVG57Nb15VNuegcS2MmMrW/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Elektrotechniki i Elektroniki",
        "Typ": "WYK",
        "Opis": "Przerobione materiały z elektroniki.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Długie", "Tag_Red"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "All-In-One Przykłady Ze Statystyki",
        "Link": "https://docs.google.com/spreadsheets/d/10fj92JV-Dmfty0xuCGCUKZqSKCQKMgtl/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Statystyki",
        "Typ": "ĆWI",
        "Opis": "Przerobione przykłady z zajęć.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["WIP", "Tag_Black"], [".xlsx", "Tag_Green"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excele z Lekcji",
        "Link": "https://docs.google.com/spreadsheets/d/1-aGamF2Ne6W0oPxkQ3zck6miCMf2vH2Q/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Statystyka",
        "Typ": "ĆWI",
        "Opis": "Zbiór najważniejszych Excelów z zajęć.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["Z Lekcji", "Tag_Purple"], [".xlsx", "Tag_Green"], ["Zadanie Domowe", "Tag_Pink"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Teoria Ze Statystyki v1",
        "Link": "https://docs.google.com/document/d/10SUZaOgxJkb3PXj0UB24coSYJcWQtMAy/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Statystyki",
        "Typ": "ĆWI",
        "Opis": "Zbiór tematów z teorii, potrzebnych do zadań z Excela.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["WIP", "Tag_Black"], [".docx", "Tag_Blue"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Teoria Ze Statystyki v2",
        "Link": "https://docs.google.com/document/d/1-QEmk1I7nY4DHwh0eL7fzVu-X3RuTAfE/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Statystyki",
        "Typ": "ĆWI",
        "Opis": "Poprawiona wersja. Pojęcia i wzory potrzebne do zaliczenia.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Rozwiązania Zadań Z Algorytmów",
        "Link": "https://drive.google.com/file/d/1973OjdZ6UPz04QSEVSDHBfq4nAA_mXmN/view?usp=sharing",
        "Semestr": "2",
        "Przedmiot": "Algorytmy i Struktury Danych",
        "Typ": "LAB",
        "Opis": "Rozwiązania wszystkich zadań z labów z algorytmów.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["WIP", "Tag_Black"], [".ipynb", "Tag_Gray"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Teoria Z Matematyki",
        "Link": "https://docs.google.com/document/d/1yxILXqchGWLbXnCAGNScqg5EFEp4HYbJ/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Matematyka",
        "Typ": "WYK",
        "Opis": "Notatka z teorii z wykładów z matematyki.",
        "Data Dodania": "14.06.2023",
        "Tagi": [["WIP", "Tag_Black"], [".docx", "Tag_Blue"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Elektronika ćw 3",
        "Link": "https://docs.google.com/spreadsheets/d/1HY7stWEnZ1YowHG9vZgPgmseE6SxrRwk/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Elektrotechniki i Elektroniki",
        "Typ": "LAB",
        "Opis": "Excel do ćwiczenia 3, zdane na 3.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Z Lekcji", "Tag_Purple"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Elektronika ćw 7/5",
        "Link": "https://docs.google.com/spreadsheets/d/1J_0RJj_-J1dynB0Vv9jdXWLL2eh4UWQU/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Elektrotechniki i Elektroniki",
        "Typ": "LAB",
        "Opis": "Excel do ćwiczenia 7(✓)/5, zdane na 4.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Elektronika ćw 2/6",
        "Link": "https://docs.google.com/spreadsheets/d/1JFYd7r5S_MBxlTYYJPDDBq6Z4ao3xE5R/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Elektrotechniki i Elektroniki",
        "Typ": "LAB",
        "Opis": "Excel do ćwiczenia 2(✓)/6, zdane na 3.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Elektronika ćw 1/8",
        "Link": "https://docs.google.com/spreadsheets/d/1J3xDo-j3gUQ1wL6trJYpxKbh_JqvGP-6/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Elektrotechniki i Elektroniki",
        "Typ": "LAB",
        "Opis": "Excel do ćwiczenia 1(✓)/8, zdane na 3.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Elektronika ćw 9/10",
        "Link": "https://docs.google.com/spreadsheets/d/1J-sYPjIYjMSaDtsouH8q1j1ZRm3ZIMQJ/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "2",
        "Przedmiot": "Podstawy Elektrotechniki i Elektroniki",
        "Typ": "LAB",
        "Opis": "Excel do ćwiczenia 9/10(✓), zdane na 3.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },

    //! TODO: Semestr 1
    {
        "Nazwa": "Polecenia Cisco",
        "Link": "https://docs.google.com/document/d/1VoiaElkw0o0K4ZVoQ3-rkYqZLedokKEp/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "1",
        "Przedmiot": "CCNA",
        "Typ": "LAB",
        "Opis": "Spis poleceń używanych na labach i zaliczeniu z CCNA.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Zagadnienia Z Programowania",
        "Link": "https://docs.google.com/document/d/1WYgtHKWydYKh0K-F7NbaZlfTcUCoXwmu70V01F51Nww/edit?usp=sharing",
        "Semestr": "1",
        "Przedmiot": "Wstęp Do Programowania",
        "Typ": "LAB",
        "Opis": "Spis tematów z wykładów z programowania, bardzo ogólnikowe.",
        "Data Dodania": "14.06.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Notatka z Matematyki",
        "Link": "https://docs.google.com/document/d/1x_85mMR_02eGATe_rWWXc6_oNRTHH66j/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "1",
        "Przedmiot": "Podstawy Matematyki",
        "Typ": "WYK",
        "Opis": "Notatki z wykładów z matematyki.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Notatka z Fizyki",
        "Link": "https://docs.google.com/document/d/15k7yBwZ-QdCQ_HDQshMaIwxe-9IEMiOFM9kUSvw8CwU/edit?usp=sharing",
        "Semestr": "1",
        "Przedmiot": "Fizyka",
        "Typ": "WYK",
        "Opis": "Notatka z wykładów z fizyki.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["WIP", "Tag_Black"], ["Złe Formatowanie", "Tag_Orange"], ["Długie", "Tag_Red"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Najważniejsze Informacje z LAB Programowania",
        "Link": "https://docs.google.com/document/d/1Hq0S9TawNEr-tWtAA-PE4hPPjvH8EFTr/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "1",
        "Przedmiot": "Wstęp Do Programowania",
        "Typ": "LAB",
        "Opis": "Zbiór najważniejszych informacji z wstępu z programowania.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".docx", "Tag_Blue"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Fizyka Ćw 6",
        "Link": "https://docs.google.com/spreadsheets/d/1iAM1QH7IIns4JK3P5mWgVsIbAS7NmlzSnk6D_VkGKR0/edit?usp=sharing",
        "Semestr": "1",
        "Przedmiot": "Fizyka",
        "Typ": "LAB",
        "Opis": "Excel do ćw 6 z LAB Fizyki.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Fizyka Ćw 1",
        "Link": "https://docs.google.com/spreadsheets/d/1fPMItt8Al06e2F3D1TzrfA-y8X4JCFKa/edit?usp=sharing&ouid=100657602081476731659&rtpof=true&sd=true",
        "Semestr": "1",
        "Przedmiot": "Fizyka",
        "Typ": "LAB",
        "Opis": "Excel do ćw 1 z LAB Fizyki.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Fizyka Ćw 2",
        "Link": "https://docs.google.com/spreadsheets/d/1YmordHLPksONGAcTJKcE3FhHQvd8GLH8FmmMqXFGjBw/edit?usp=sharing",
        "Semestr": "1",
        "Przedmiot": "Fizyka",
        "Typ": "LAB",
        "Opis": "Excel do ćw 2 z LAB Fizyki.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Fizyka Ćw 3",
        "Link": "https://docs.google.com/spreadsheets/d/1XjIspm4c9BwPCKxv7QzAgcir34uC1AxKKhD-86BBUok/edit?usp=drive_link",
        "Semestr": "1",
        "Przedmiot": "Fizyka",
        "Typ": "LAB",
        "Opis": "Excel do ćw 3 z LAB Fizyki.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
    {
        "Nazwa": "Excel Fizyka Ćw 4",
        "Link": "https://docs.google.com/spreadsheets/d/1QvHH6tolJu5Q-fmyTu1Y6je4kX1QhbVwDikGKsp9Ytc/edit?usp=sharing",
        "Semestr": "1",
        "Przedmiot": "Fizyka",
        "Typ": "LAB",
        "Opis": "Excel do ćw 4 z LAB Fizyki.",
        "Data Dodania": "16.07.2023",
        "Tagi": [[".xlsx", "Tag_Green"], ["Możliwe Błędy", "Tag_Lime"], ["Studia Dzienne", "Tag_Brown"]],
        "Autor": "Hubsik",
    },
]
